@startuml
'https://plantuml.com/component-diagram


component configuration {
}

component camera {
  component imageproducer
  component calibration


}

component board_extractor {

}

component led_extractor {

}

component blink_detection {
}

component publisher {
}

@enduml