@startuml

actor user


note over labgrid_client: the labgrid sequence isn't final!


user -> labgrid_client: labgrid-client -p <place> acquire
labgrid_client -> labgrid_coordinator:  acquire <place> boss
labgrid_coordinator -> place: check acquire
place --> labgrid_coordinator: True
labgrid_coordinator --> labgrid_client: True
labgrid_client --> user: "place acquired"
user -> labgrid_client: labgrid-client -p <place> console
labgrid_client -> boss_publisher: open_connection
activate boss_publisher
boss_publisher --> user: session
note over boss_publisher
    The configuration is shown
    in another sequence diagram!
end note
note over user: only changes setting

user -> boss_publisher: subscribe(ids=["led_1", "led_2"], mode="only_changes")

hnote over boss_publisher: led_1 changed it's color
boss_publisher --> user: "led_1: active True, color=green time: 1234567"

note over user: poll setting

user -> boss_publisher: subscribe(ids=["led_1", "led_2"], mode= poll, interval=1)

loop interval every sec
    boss_publisher --> user: "led_1: {<<current state>>} ,led_2:{<<current_state}"
end



@enduml