@startuml




package classifier{
    [board_classifier]
    [led_classifier]
}
package camera{


package extractor{

    [camera_extractor]
    note left of camera_extractor: - reads camera_feed\n- calibrates camera
    [board_extractor]
    [led_extractor]
    note left of board_extractor: - extract roi of controller board from image\n- reshape image\n- correct image orientation
    [board_extractor] .left.> [board_classifier]: get_informations
    [led_extractor] -- [state_detector]
    note left of led_extractor: - extracts roi for leds
    note left of state_detector: - checks if led is either "on", "off" or "blinking"
}
webcam <-- [camera_extractor]: open

package publisher{
    [labgrid_publisher]

}
[state_detector] .left.> [frequence_detector]: uses





@enduml