name: deploy

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    container:
      image: ictu/sshpass
    steps:
    - name: deploy action
      run: sshpass -p ${{ secrets.SERVER_PW }} ssh -o "StrictHostKeyChecking=no" root@89.58.3.45 "echo here" - ${GITHUB_REF##*/} #${{ inputs.branch }},