name: deploy

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    container:
      image: ictu/sshpass
    steps:
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: deploy action
      env:
        SUPER_SECRET: ${{ secrets.SERVER_PW }}
      run: sshpass -p test"$SUPER_SECRET" ssh -o "StrictHostKeyChecking=no" gitrunner@89.58.3.45 "echo here + ${{ steps.extract_branch.outputs.branch }}" #${{ inputs.branch }},