name: deploy

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    container:
      image: ictu/sshpass
    steps:
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: deploy action
      run: sshpass -p ${{ secrets.SERVER_PW }} ssh -o "StrictHostKeyChecking=no" root@89.58.3.45 "echo here + ${{ steps.extract_branch.outputs.branch }}" #${{ inputs.branch }},