name: deploy

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    container:
      image: ictu/sshpass
    steps:
    #- name: Extract branch name
    #  shell: bash
    #  run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    #  id: extract_branch

    - name: deploy action
      env:
        SERVER_PW: ${{ secrets.SERVER_PW }}
      run: sshpass -p "1234" ssh -o "StrictHostKeyChecking=no" gittest@89.58.3.45 "echo here" #${{ inputs.branch }},